### ISSUE TITLE
scrolling stops responding after visiting map page

### ISSUE THREAD

**Issue by adrq** [DigitalUSSouth/NativeAmericanSCArchive#6]
Scrolling will not work after visiting the map page.

Steps to reproduce:
- open website
- select any link(s) in menu (except "Map") and note that scrolling works.
- select "Map"
- select any of the other tabs
- scrolling no longer works

@Jendrasi Do you know what might be causing this?

**Comment by Jendrasi** [comment]
Issue is fixed on 'tribes/main' branch. We can merge it once I've got the last bits of tribes ready.
