### ISSUE TITLE
PHP Notice hiding behind nav bar and offsetting body

### ISSUE THREAD

**Issue by Jendrasi** [DigitalUSSouth/NativeAmericanSCArchive#9]
Notice: Undefined index: page in NASCA-site/index.php on line 14

**Comment by adrq** [comment]
Unable to reproduce, but I added some code to check that we have a valid $_GET object before trying to access it. See commit ec630b9

**Comment by adrq** [comment]
Let me know if you still get this error.

**Comment by Jendrasi** [comment]
I stopped seeing this issue around the time of that commit. Didn't see your comment on this until now. I think it's fixed.
